#############
### build ###
#############

FROM node:12.2.0 as build

RUN wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
RUN apt-get update && apt-get install -yq google-chrome-stable

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY vestbirk/package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

COPY vestbirk/ /app

#RUN ng test --watch=false
#RUN ng e2e --port 4202

RUN ng build --output-path=dist

############
### prod ###
############

FROM nginx:1.16.0-alpine

COPY --from=build /app/dist /usr/share/nginx/html 
COPY ./nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

