setup: &default
    docker:
        - image: circleci/node:12.2.0
    working_directory: ~/repo

version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build

    build-prod:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build production image
                command: |
                    make build-prod

    push_image:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                Name: Login to Canister
                command: |
                    docker login --username $DOCKER_USER --password $DOCKER_PASSWORD cloud.canister.io:5000
            - run:
                Name: Build and push image
                command: |
                    make build-prod
                    docker push cloud.canister.io:5000/jenshenrik/vestbirk-frontend

    test:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build and Test
                command: |
                    make test

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build
                filters:
                    branches:
                        ignore: master

    production:
        jobs:
            - build-prod
            - test:
                requires:
                    - build-prod
            - push_image:
                requires:
                    - test
                filters:
                    branches:
                        only: master
