setup: &default
    docker:
        - image: circleci/node:12.2.0
    working_directory: ~/repo

master_only: &master-only
    filters:
        branches:
            only:
                - master

version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build

    build-prod:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build production image
                command: |
                    make build-prod

    test:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build and Test
                command: |
                    make test

    push_image:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                Name: Login to Canister
                command: |
                    docker login --username $DOCKER_USER --password $DOCKER_PASSWORD cloud.canister.io:5000
            - run:
                Name: Build and push image
                command: |
                    make build-prod
                    docker push cloud.canister.io:5000/jenshenrik/vestbirk-frontend:prod

    deploy:
        machine:
            enabled: true
        steps:
            - add_ssh_keys:
                fingerprints:
                    - "52:f3:eb:62:6b:f6:15:23:87:0a:1d:61:d6:b4:54:d8"
            - run:
                name: Deploy over SSH
                command: |
                    ssh $SSH_USER@$SSH_HOST "./deploy-vestbirk-frontend.sh"


workflows:
    version: 2
    build_and_test:
        jobs:
            - build:
                filters:
                    branches:
                        ignore: master
            - test:
                requires:
                    - build
                filters:
                    branches:
                        ignore: master

    production:
        jobs:
            - build-prod:
                <<: *master-only
            - test:
                requires:
                    - build-prod
                <<: *master-only
            - push_image:
                requires:
                    - test
                <<: *master-only
            - deploy:
                requires:
                    - push_image
                <<: *master-only

