setup: &default
    docker:
        - image: circleci/node:12.2.0
    working_directory: ~/repo

version: 2

jobs:
    build:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build
                command: |
                    make build

    test:
        <<: *default
        steps:
            - setup_remote_docker
            - checkout
            - run:
                name: Build and Test
                command: |
                    make test

workflows:
    version: 2
    build_and_test:
        jobs:
            - build
            - test:
                requires:
                    - build

